using OnlineBookingAggregatorApp.Core;
using OnlineBookingAggregatorApp.Domain.Entities;

namespace OnlineBookingAggregatorApp.Domain.Enums
{
    public enum BusinessArea
    {
        [ParentEnum(nameof(BusinessType.Beauty))] BeautSalon = 1,
        [ParentEnum(nameof(BusinessType.Beauty))] Barbershop,
        [ParentEnum(nameof(BusinessType.Beauty))] PrivateEmployee,
        [ParentEnum(nameof(BusinessType.Beauty))] KidsHairdresser,
        [ParentEnum(nameof(BusinessType.Beauty))] Spa,
        [ParentEnum(nameof(BusinessType.Beauty))] Tattoo,
        [ParentEnum(nameof(BusinessType.Beauty))] Cosmetology,
        [ParentEnum(nameof(BusinessType.Beauty))] EyebrowsAndEyelashes, 
        [ParentEnum(nameof(BusinessType.Beauty))] NailService,
        [ParentEnum(nameof(BusinessType.Beauty))] Waxing,
        [ParentEnum(nameof(BusinessType.Beauty))] OtherBeautyServices,
        [ParentEnum(nameof(BusinessType.Beauty))] OtherBeautyBusiness,
        [ParentEnum(nameof(BusinessType.Healthcare))] MedicalCenter,
        [ParentEnum(nameof(BusinessType.Healthcare))] Dentist,
        [ParentEnum(nameof(BusinessType.Healthcare))] VetClinic,
        [ParentEnum(nameof(BusinessType.Healthcare))] Analysis,
        [ParentEnum(nameof(BusinessType.Healthcare))] PsychotherapyAndPsychology,
        [ParentEnum(nameof(BusinessType.Healthcare))] AlternativeMedicine,
        [ParentEnum(nameof(BusinessType.Healthcare))] Hospital,
        [ParentEnum(nameof(BusinessType.Healthcare))] Polyclinic,
        [ParentEnum(nameof(BusinessType.Healthcare))] DiagnosticCenter,
        [ParentEnum(nameof(BusinessType.Healthcare))] WomenConsultation,
        [ParentEnum(nameof(BusinessType.Healthcare))] WellnessMassage,
        [ParentEnum(nameof(BusinessType.Healthcare))] OtherMedicalBusiness,
        [ParentEnum(nameof(BusinessType.Sport))] FitnessClub,
        [ParentEnum(nameof(BusinessType.Sport))] SportSchool,
        [ParentEnum(nameof(BusinessType.Sport))] DanceSchool,
        [ParentEnum(nameof(BusinessType.Sport))] TennisAndSquash,
        [ParentEnum(nameof(BusinessType.Sport))] SwimmingPool,
        [ParentEnum(nameof(BusinessType.Sport))] TrampolineCenter,
        [ParentEnum(nameof(BusinessType.Sport))] Ems,
        [ParentEnum(nameof(BusinessType.Sport))] PersonalCoach,
        [ParentEnum(nameof(BusinessType.Sport))] Yoga,
        [ParentEnum(nameof(BusinessType.Sport))] PrivateServices,
        [ParentEnum(nameof(BusinessType.Sport))] OtherSport,
        [ParentEnum(nameof(BusinessType.Education))] MultidisciplinaryCourses,
        [ParentEnum(nameof(BusinessType.Education))] KidsWorkshop,
        [ParentEnum(nameof(BusinessType.Education))] LanguageSchool,
        [ParentEnum(nameof(BusinessType.Education))] SchoolOfMusic,
        [ParentEnum(nameof(BusinessType.Education))] TestPreparation,
        [ParentEnum(nameof(BusinessType.Education))] DrivingSchool,
        [ParentEnum(nameof(BusinessType.Education))] OtherEducation,
        [ParentEnum(nameof(BusinessType.Entertainment))] Sauna,
        [ParentEnum(nameof(BusinessType.Entertainment))] Bowling,
        [ParentEnum(nameof(BusinessType.Entertainment))] CyberSport,
        [ParentEnum(nameof(BusinessType.Entertainment))] Quest,
        [ParentEnum(nameof(BusinessType.Entertainment))] Restaurant,
        [ParentEnum(nameof(BusinessType.Entertainment))] MassageSalon,
        [ParentEnum(nameof(BusinessType.Entertainment))] Karting,
        [ParentEnum(nameof(BusinessType.Entertainment))] OtherEntertainment,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] PhotoStudio,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] Atelier,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] DryCleaning,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] Cleaning,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] EquipmentRepair,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] ZooServices,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] EquipmentRental,
        [ParentEnum(nameof(BusinessType.HouseholdServices))] OtherHouseholdServices,
        [ParentEnum(nameof(BusinessType.Auto))] CarWash,
        [ParentEnum(nameof(BusinessType.Auto))] AutoBodyShop,
        [ParentEnum(nameof(BusinessType.Auto))] CarShowroom,
        [ParentEnum(nameof(BusinessType.Auto))] TuningCenter,
        [ParentEnum(nameof(BusinessType.Auto))] VehicleInspection,
        [ParentEnum(nameof(BusinessType.Auto))] DetailingCenter,
        [ParentEnum(nameof(BusinessType.Auto))] PrivateMechanic,
        [ParentEnum(nameof(BusinessType.Auto))] TyreShop,
        [ParentEnum(nameof(BusinessType.Auto))] CarRental,
        [ParentEnum(nameof(BusinessType.Auto))] AnotherAutoBusiness,
        [ParentEnum(nameof(BusinessType.Retail))] OpticsSalon,
        [ParentEnum(nameof(BusinessType.Retail))] CosmeticsStore,
        [ParentEnum(nameof(BusinessType.Retail))] FurnitureAndInterior,
        [ParentEnum(nameof(BusinessType.Retail))] FoodStore,
        [ParentEnum(nameof(BusinessType.Retail))] BookStore,
        [ParentEnum(nameof(BusinessType.Retail))] ShoppingCenter,
        [ParentEnum(nameof(BusinessType.Retail))] BoutiqueAndShowroom,
        [ParentEnum(nameof(BusinessType.Retail))] WeddingSalon,
        [ParentEnum(nameof(BusinessType.Retail))] OtherRetail,
        [ParentEnum(nameof(BusinessType.Other))]Notary,
        [ParentEnum(nameof(BusinessType.Other))]AccountingAndAuditing,
        [ParentEnum(nameof(BusinessType.Other))]EventManagement,
        [ParentEnum(nameof(BusinessType.Other))]LawFirm,
        [ParentEnum(nameof(BusinessType.Other))]RealEstate,
        SelfEmployedSpecialist,
    }

     public class BusinessAreaEntity : EnumEntity<BusinessArea>
    {
        public BusinessAreaEntity()
        {
        }

        internal BusinessAreaEntity(BusinessArea id, string name, long parentId = 0) : base(id, name, parentId)
        {
        }
    }

    public class BusinessAreaEntityFactory : EnumEntityFactory<BusinessArea, BusinessAreaEntity>
    {
        public static BusinessAreaEntityFactory Instance { get; } = new BusinessAreaEntityFactory();

        public BusinessAreaEntityFactory()
        {
            Register(
                new BusinessAreaEntity(BusinessArea.BeautSalon, "Beauty Salon", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.Barbershop, "Barber Shop", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.PrivateEmployee, "Private Employee", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.KidsHairdresser, "Kids Hairdresser", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.Spa, "SPA", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.Tattoo, "Tattoo", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.Cosmetology, "Cosmetology", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.EyebrowsAndEyelashes, "Eyebrows And Eyelashes", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.NailService, "Nail Service", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.Waxing, "Waxing", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.OtherBeautyServices, "Other Beauty Services", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.OtherBeautyBusiness, "Other Beauty Business", (long) BusinessType.Beauty),
                new BusinessAreaEntity(BusinessArea.MedicalCenter, "Medical Center", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.Dentist, "Dentist", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.VetClinic, "Vet Clinic", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.Analysis, "Analysis", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.PsychotherapyAndPsychology, "Psychotherapy And Psychology", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.AlternativeMedicine, "Alternative Medicine", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.Hospital, "Hospital", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.Polyclinic, "Polyclinic", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.DiagnosticCenter, "Diagnostic Center", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.WomenConsultation, "Women's Consultation", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.WellnessMassage, "Wellness Massage", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.OtherMedicalBusiness, "Other Medical Business", (long) BusinessType.Healthcare),
                new BusinessAreaEntity(BusinessArea.FitnessClub, "Fitness Club", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.SportSchool, "Sport School", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.DanceSchool, "Dance School", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.TennisAndSquash, "Tennis And Squash", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.SwimmingPool, "Swimming Pool", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.TrampolineCenter, "Trampoline Center", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.Ems, "EMS", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.PersonalCoach, "Personal Coach", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.Yoga, "Yoga", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.PrivateServices, "Private Services", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.OtherSport, "Other Sport", (long) BusinessType.Sport),
                new BusinessAreaEntity(BusinessArea.MultidisciplinaryCourses, "Multidisciplinary Courses", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.KidsWorkshop, "Kids Workshop", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.LanguageSchool, "Language School", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.SchoolOfMusic, "School of Music", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.TestPreparation, "Test Preparation", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.DrivingSchool, "Driving School", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.OtherEducation, "Other Education", (long) BusinessType.Education),
                new BusinessAreaEntity(BusinessArea.Sauna, "Sauna", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.Bowling, "Bowling", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.CyberSport, "Cyber Sport", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.Quest, "Quest", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.Restaurant, "Restaurant", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.MassageSalon, "Massage Salon", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.Karting, "Karting", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.OtherEntertainment, "Other Entertainment", (long) BusinessType.Entertainment),
                new BusinessAreaEntity(BusinessArea.PhotoStudio, "Photo Studio", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.Atelier, "Atelier", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.DryCleaning, "Dry Cleaning", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.Cleaning, "Cleaning", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.EquipmentRepair, "Equipment Repair", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.ZooServices, "Zoo Services", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.EquipmentRental, "Equipment Rental", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.OtherHouseholdServices, "Other Household Services", (long) BusinessType.HouseholdServices),
                new BusinessAreaEntity(BusinessArea.CarWash, "Car Wash", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.AutoBodyShop, "Auto Body Shop", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.CarShowroom, "Car Showroom", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.TuningCenter, "Tuning Center", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.VehicleInspection, "Vehicle Inspection", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.DetailingCenter, "Detailing Center", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.PrivateMechanic, "Private Mechanic", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.TyreShop, "Tyre Shop", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.CarRental, "Car Rental", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.AnotherAutoBusiness, "Another Auto Business", (long) BusinessType.Auto),
                new BusinessAreaEntity(BusinessArea.OpticsSalon, "Optics Salon", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.CosmeticsStore, "Cosmetics Store", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.FurnitureAndInterior, "Furniture And Interior", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.FoodStore, "Food Store", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.BookStore, "Book Store", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.ShoppingCenter, "Shopping Center", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.BoutiqueAndShowroom, "Boutique And Showroom", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.WeddingSalon, "Wedding Salon", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.OtherRetail, "Other Retail", (long) BusinessType.Retail),
                new BusinessAreaEntity(BusinessArea.Notary, "Notary", (long) BusinessType.Other),
                new BusinessAreaEntity(BusinessArea.LawFirm, "Law Firm", (long) BusinessType.Other),
                new BusinessAreaEntity(BusinessArea.AccountingAndAuditing, "Accounting And Auditing", (long) BusinessType.Other),
                new BusinessAreaEntity(BusinessArea.EventManagement, "Event Management", (long) BusinessType.Other),
                new BusinessAreaEntity(BusinessArea.RealEstate, "RealEstate", (long) BusinessType.Other),
                new BusinessAreaEntity(BusinessArea.SelfEmployedSpecialist, "Self-employed Specialist")
            );
        }
    }
}