WHILE( NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SeriLog' ))

BEGIN
	CREATE TABLE SeriLog
	(
		Id BIGSERIAL PRIMARY KEY,
		Message VARCHAR NULL,
		MessageTemplate VARCHAR NULL,
		LogLevel VARCHAR (128) NULL,
		Time_Stamp TIMESTAMP NOT NULL,
		Exception VARCHAR NULL,
		Properties VARCHAR NULL
	)
END