// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineBookingAggregatorApp.Persistence.Data;

namespace OnlineBookingAggregatorApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210221164825_Remove_Index_From_Position_Name")]
    partial class Remove_Index_From_Position_Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialistId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("ClientCategory")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCategory");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Gender");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BusinessType")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<long>("CompanyType")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeesSize")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessType");

                    b.HasIndex("CompanyType");

                    b.HasIndex("EmployeesSize");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyBusinessAreas");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("Policy")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<long>("Role")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.HasKey("Id");

                    b.HasIndex("Policy");

                    b.HasIndex("Role");

                    b.ToTable("PolicyRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25811fe8-09e9-448b-84aa-525e2f87b855"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(5172), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 1L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("b1d7fc37-aa1c-4324-8849-cc92676bdf92"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(6663), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 1L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("243ef69f-54e2-4129-a7e9-e12e8a595bf4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(8103), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 2L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("e21d5053-643e-49f4-8bcd-86ae918d4590"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(8135), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 2L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("c1274f69-8c1a-4a96-bae6-a76f458be4da"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(8498), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 3L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("300b75cf-4ae2-4c3f-befb-a4f22d79ab40"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(8976), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("ef07943d-9faa-4ed3-b658-87e02078ce0c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9006), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("cf900e09-9dcb-40a2-9283-24eaa5b2ccf4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9032), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("69f7cb60-019e-4136-9d2f-9e8090baee44"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9299), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 5L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("7d686dbd-412c-4b07-8189-c02a973cdeb0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9330), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 5L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("1e1d3490-0f4b-4c1e-a903-8ee9dad9281c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9606), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("3ad5f9d8-81cc-482f-8b8f-18d0cdc98298"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9638), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("0769a4d1-4bab-45c3-a343-b9ea9ad29049"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9664), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("c3b139e1-0d84-4d52-b0d0-e4b9084d41cb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9919), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 7L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("57161a92-2a40-436e-b65c-e752334dc62f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 105, DateTimeKind.Unspecified).AddTicks(9946), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 7L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("fc14fdfa-d7d7-45f4-aaed-29943d060476"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(198), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 8L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("479628d9-df14-4830-8090-0c12c26866c2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(226), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 8L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("0d5ec643-7e81-4113-878e-0ed22e39f073"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(587), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("7c73e726-5065-42ff-84cf-514626ae66ae"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(614), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("6c22de85-95cb-4289-a96c-9261b2be26ae"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(641), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("bb3142aa-f197-4cbd-84e8-07d4ad149834"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(894), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 10L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("9264b992-ae58-4929-8432-472ef651b608"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1148), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 11L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("273122fb-6b12-40dd-9958-26ee2e8345e0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1175), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 11L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("aa2871af-9050-4b67-b243-52a774368584"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1506), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("539f5bdf-21e5-48a9-aa7f-5464fec5a438"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1534), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("4c4ce230-d42a-4ce0-8929-885c11a43c5c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1562), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("8e251c35-ad9d-4314-8d35-53125edd7cdf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1821), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("2dfed48d-ccc2-4349-9b46-1c4f33108e86"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1848), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("ffbb5436-8275-495b-8460-8a0cdb7ebe6a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(1874), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("b3eac3ce-2001-43f4-b4d9-afa18d545e2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2123), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("4dda3fcc-d1ac-47b4-ac54-4e1755e42a79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2150), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("973de4f6-775c-4146-acac-a23fddf8137e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2176), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("f2bd7aed-87d8-4bd9-a196-7a6fa1c7e300"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2469), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 15L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("d1386472-9129-4832-b6ea-4d2800f84b99"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2499), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 15L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("98f9b4c7-8fa7-4364-a0ed-059d6b60f733"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(2800), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 16L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("196b17e4-4366-43f3-8a21-1edeb6035b0b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(3047), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 17L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("f57fc481-5212-4c1b-b7a5-c6fd4741e1ea"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(3286), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 18L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("e21b69d8-1b2c-49ac-93ed-9c27b73f4692"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 21, 16, 48, 24, 106, DateTimeKind.Unspecified).AddTicks(3313), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 18L,
                            Role = 2L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceEmployees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Information")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SystemRole")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Gender");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PositionId");

                    b.HasIndex("SystemRole");

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DayType")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartingWorkAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WeekendType")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<int>("WorkingHoursFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingHoursTo")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayType");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekendType");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BusinessAreas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty Salon",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Barber Shop",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Private Employee",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Kids Hairdresser",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "SPA",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Tattoo",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Cosmetology",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Eyebrows And Eyelashes",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Nail Service",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Waxing",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Other Beauty Services",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Other Beauty Business",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Medical Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dentist",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Vet Clinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Analysis",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Psychotherapy And Psychology",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Alternative Medicine",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Hospital",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Polyclinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Diagnostic Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Women's Consultation",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Wellness Massage",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Other Medical Business",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Fitness Club",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Sport School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Dance School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Tennis And Squash",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Swimming Pool",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Trampoline Center",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            Name = "EMS",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Personal Coach",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Yoga",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Private Services",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Other Sport",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Multidisciplinary Courses",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Kids Workshop",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Language School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            Name = "School of Music",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Test Preparation",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Driving School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Other Education",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Sauna",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Bowling",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Cyber Sport",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Quest",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Restaurant",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Massage Salon",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Karting",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Other Entertainment",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Photo Studio",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Atelier",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Dry Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Equipment Repair",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Zoo Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Equipment Rental",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Other Household Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Car Wash",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Auto Body Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Car Showroom",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Tuning Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Vehicle Inspection",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Detailing Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Private Mechanic",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Tyre Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Car Rental",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Another Auto Business",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Optics Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Cosmetics Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Furniture And Interior",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Food Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Book Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Shopping Center",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Boutique And Showroom",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 76L,
                            Name = "Wedding Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Other Retail",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Notary",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Law Firm",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Accounting And Auditing",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Event Management",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 82L,
                            Name = "RealEstate",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Self-employed Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Healthcare",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Sport",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Education",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Entertainment",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "HouseholdServices",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Auto",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Retail",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Other",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Loyal",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Permanent",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "VIP",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = 0L,
                            Name = "Juridical Person",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 1L,
                            Name = "Physical Person",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DayTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Work Day",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Weekend",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SizeOfEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "1",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "2-5",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "6-10",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "11-20",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "21+",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Male",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Female",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CanViewEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CanManageEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "CanAddEmployee",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "CanChangeEmployeeWorkSchedule",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "CanManagePositions",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CanViewClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CanManageClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "CanAddService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "CanEditService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "CanDeleteService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "CanViewOtherPeoplesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "CanCreateBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "CanAmendBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "CanRemoveBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "CanAmendOtherEmployeesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "CanEditRoles",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "CanManageRolePolicies",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "CanEditCompanyInfo",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CompanyAdmin",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CompanyAdminDeputy",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WeekendTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Sick",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Leave",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Paid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Unpaid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Standard Weekend (SAT/SUN)",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Absence",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Specialist")
                        .WithMany("AssignedBookings")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeesSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("CompanyBusinessAreas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("Policy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany("ServiceEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany("ServiceEmployees")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("DayType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("WeekendType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CompanyBusinessAreas");

                    b.Navigation("Employees");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceEmployees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedBookings");

                    b.Navigation("ServiceEmployees");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
