// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineBookingAggregatorApp.Persistence.Data;

namespace OnlineBookingAggregatorApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210228194108_RemoveDefaultValueFromIsSetByDefaultInPolicyRole")]
    partial class RemoveDefaultValueFromIsSetByDefaultInPolicyRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BookingId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialistId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CategoryId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ServiceTargetGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(3L)
                        .HasColumnName("ServiceTargetGroupId");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ServiceTargetGroup");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ClientId")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("ClientCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientCategory");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Gender");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyId")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BusinessType")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<long>("CompanyType")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeesSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessType");

                    b.HasIndex("CompanyType");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeesSize");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyBusinessAreaId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("CompanyBusinessAreas");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyRoleId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSetByDefault")
                        .HasColumnType("boolean");

                    b.Property<long>("Policy")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<long>("Role")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Role");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Policy", "Role")
                        .IsUnique();

                    b.ToTable("PolicyRoles");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PositionId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceEmployeeId")
                        .UseIdentityByDefaultColumn();

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ServiceEmployees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long>("EmployeeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("EmployeeStatusId");

                    b.Property<DateTimeOffset?>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Information")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("OnHolidayFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OnHolidayTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SystemRole")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeStatus");

                    b.HasIndex("Gender");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PositionId");

                    b.HasIndex("SystemRole");

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("DayType")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SystemCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WeekendType")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<int>("WorkingHoursFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingHoursTo")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayType");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekendType");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BusinessAreas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty Salon",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Barber Shop",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Private Employee",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Kids Hairdresser",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "SPA",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Tattoo",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Cosmetology",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Eyebrows And Eyelashes",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Nail Service",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Waxing",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Other Beauty Services",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Other Beauty Business",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Medical Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dentist",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Vet Clinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Analysis",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Psychotherapy And Psychology",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Alternative Medicine",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Hospital",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Polyclinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Diagnostic Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Women's Consultation",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Wellness Massage",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Other Medical Business",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Fitness Club",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Sport School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Dance School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Tennis And Squash",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Swimming Pool",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Trampoline Center",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            Name = "EMS",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Personal Coach",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Yoga",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Private Services",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Other Sport",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Multidisciplinary Courses",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Kids Workshop",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Language School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            Name = "School of Music",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Test Preparation",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Driving School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Other Education",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Sauna",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Bowling",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Cyber Sport",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Quest",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Restaurant",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Massage Salon",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Karting",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Other Entertainment",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Photo Studio",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Atelier",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Dry Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Equipment Repair",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Zoo Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Equipment Rental",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Other Household Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Car Wash",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Auto Body Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Car Showroom",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Tuning Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Vehicle Inspection",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Detailing Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Private Mechanic",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Tyre Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Car Rental",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Another Auto Business",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Optics Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Cosmetics Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Furniture And Interior",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Food Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Book Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Shopping Center",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Boutique And Showroom",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 76L,
                            Name = "Wedding Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Other Retail",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Notary",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Law Firm",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Accounting And Auditing",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Event Management",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 82L,
                            Name = "RealEstate",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Self-employed Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Healthcare",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Sport",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Education",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Entertainment",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "HouseholdServices",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Auto",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Retail",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Other",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Loyal",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Permanent",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "VIP",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = 0L,
                            Name = "Juridical Person",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 1L,
                            Name = "Physical Person",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DayTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Work Day",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Weekend",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.EmployeeStatusEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeStatusId");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "An employee is currently active.",
                            Icon = "person",
                            Name = "Active",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "An employee is currently on holiday.",
                            Icon = "logout",
                            Name = "On Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "An employee is hidden for some reason.",
                            Icon = "person_outline",
                            Name = "Hidden",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "An employee is fired, but not removed from the system.",
                            Icon = "person_off",
                            Name = "Fired",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SizeOfEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "1",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "2-5",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "6-10",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "11-20",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "21+",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Male",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Female",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CanViewEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CanManageEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "CanAddEmployee",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "CanChangeEmployeeWorkSchedule",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "CanManagePositions",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CanViewClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CanManageClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "CanAddService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "CanEditService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "CanDeleteService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "CanViewOtherPeoplesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "CanCreateBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "CanAmendBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "CanRemoveBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "CanAmendOtherEmployeesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "CanEditRoles",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "CanManageRolePolicies",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "CanEditCompanyInfo",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.ServiceTargetGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceTargetGroupId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TargetGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Men's",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Women's",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "General",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CompanyAdmin",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CompanyAdminDeputy",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WeekendTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Sick",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Leave",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Paid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Unpaid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Standard Weekend (SAT/SUN)",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Absence",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Specialist")
                        .WithMany()
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.ServiceTargetGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("ServiceTargetGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeesSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("CompanyBusinessAreas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("Policy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.EmployeeStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeeStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("DayType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("WeekendType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CompanyBusinessAreas");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
