// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineBookingAggregatorApp.Persistence.Data;

namespace OnlineBookingAggregatorApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210214191157_Add_CustomeRoleTable")]
    partial class Add_CustomeRoleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialistId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("ClientCategory")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCategory");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Gender");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BusinessType")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<long>("CompanyType")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeesSize")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessType");

                    b.HasIndex("CompanyType");

                    b.HasIndex("EmployeesSize");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyBusinessAreas");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("Policy")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<long>("Role")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.HasKey("Id");

                    b.HasIndex("Policy");

                    b.HasIndex("Role");

                    b.ToTable("PolicyRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50062fa0-bbc7-439e-9efc-29012bd67c06"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 721, DateTimeKind.Unspecified).AddTicks(8421), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 1L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("e4602b95-331a-4258-9375-880d677011b9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(281), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 1L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("253f7351-696c-476d-91a5-0d3f4b3621ef"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(1725), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 2L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("f13319d3-6bed-44cf-b29c-293cd52a28f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(1758), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 2L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("bba9a24f-827d-411f-8ac0-8feb54edf4f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(3920), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 3L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("ac19acb6-a3bc-42ac-81d3-448581c50edb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(4393), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("777bd12c-e7f5-4ea2-99c4-00ced7f6131c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(4423), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("d3ce623d-125b-4f43-8826-63fbd1c1fc09"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(4450), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 4L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("d486f14d-c604-48a0-8095-a67e8f57290f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(4725), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 5L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("ffcf7dc3-19cb-48d3-b1d9-52db52f107d7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(4757), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 5L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("d85d3d8a-be7a-4a7b-a451-b33e0a43dfe2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(5270), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("e4d3a064-67be-41d4-a5c2-63ade83d12e9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(5304), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("347cf7c4-f4dd-459a-b0cb-3550f31d82e8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(5336), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 6L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("2595ff9f-912e-4d94-bf83-5309509499cf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(5771), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 7L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("23e355ab-f4db-4526-b7f2-19f63ce0e80c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(5807), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 7L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("7a600843-2ec9-4755-8fbe-265298f59051"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6199), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 8L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("5e717a2a-4275-4ada-9cc5-978056f709c0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6233), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 8L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("b3fc9684-4bc8-43da-85b8-b7c4eaee63d3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6562), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("c41abd0a-b863-4bc6-a198-d96f6581951c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6590), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("1610d975-7ed8-46ec-ae80-bfeda013bf1b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6616), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 9L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("239249fa-0924-4829-ad8f-0080dacf9c4f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(6863), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 10L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("a156b3a9-923d-45ba-abb3-42ded88500e3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7109), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 11L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("659fef52-2ccd-4955-ae54-cde6ed411bc2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7136), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 11L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("b768c330-5d05-4107-a746-1b78ab6b9542"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7472), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("50774a68-1182-465e-b36b-05432cbe3c91"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7499), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("8d3b61cb-cc0e-4529-854f-260e5016a6fa"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7525), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 12L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("53e2cd98-9f20-409f-8bdb-74c30c25bdc4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7769), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("2604979c-04fc-43bf-a357-f4540c1e8377"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7797), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("14c73624-7f45-47cf-98a2-88bed8f54fb2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(7823), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 13L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("fbd87b3f-5202-4ec8-8af8-56a14a64fab8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8067), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("8501cc91-865b-41ed-8c9c-65d409eeef63"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8095), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("57628abc-8b1e-431c-b832-7a0fdec7ee90"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8121), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 14L,
                            Role = 3L
                        },
                        new
                        {
                            Id = new Guid("265b53a2-6b55-43a3-8e52-3eee801fbe09"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8485), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 15L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("01e40260-dd03-4d15-9372-a759fc9e2119"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8516), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 15L,
                            Role = 2L
                        },
                        new
                        {
                            Id = new Guid("579bb1ef-2140-42b8-a62c-238158e78fae"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(8758), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 16L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("c8f386e6-8c23-4808-8bc5-911561007f68"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(9000), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 17L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("88307c68-1dea-4e5a-9f26-1d88af46f1ca"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(9441), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 18L,
                            Role = 1L
                        },
                        new
                        {
                            Id = new Guid("8ee98176-54d7-4228-bfcf-73968e884aaa"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 2, 14, 19, 11, 55, 722, DateTimeKind.Unspecified).AddTicks(9472), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0L,
                            Policy = 18L,
                            Role = 2L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BusinessArea")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessArea");

                    b.HasIndex("CompanyId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceEmployees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Information")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SystemRole")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Gender");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PositionId");

                    b.HasIndex("SystemRole");

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DayType")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartingWorkAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WeekendType")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<int>("WorkingHoursFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingHoursTo")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingMinutesTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayType");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekendType");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessAreaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BusinessAreas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty Salon",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Barber Shop",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Private Employee",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Kids Hairdresser",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "SPA",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Tattoo",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Cosmetology",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Eyebrows And Eyelashes",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Nail Service",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Waxing",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Other Beauty Services",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Other Beauty Business",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Medical Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dentist",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Vet Clinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Analysis",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Psychotherapy And Psychology",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Alternative Medicine",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Hospital",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Polyclinic",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Diagnostic Center",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Women's Consultation",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Wellness Massage",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Other Medical Business",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Fitness Club",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Sport School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Dance School",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Tennis And Squash",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Swimming Pool",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Trampoline Center",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            Name = "EMS",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Personal Coach",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Yoga",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Private Services",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Other Sport",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Multidisciplinary Courses",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Kids Workshop",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Language School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            Name = "School of Music",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Test Preparation",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Driving School",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Other Education",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Sauna",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Bowling",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Cyber Sport",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Quest",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Restaurant",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Massage Salon",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Karting",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Other Entertainment",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Photo Studio",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Atelier",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Dry Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Cleaning",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Equipment Repair",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Zoo Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Equipment Rental",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Other Household Services",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Car Wash",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Auto Body Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Car Showroom",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Tuning Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Vehicle Inspection",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Detailing Center",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Private Mechanic",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Tyre Shop",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Car Rental",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Another Auto Business",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Optics Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Cosmetics Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Furniture And Interior",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Food Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Book Store",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Shopping Center",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Boutique And Showroom",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 76L,
                            Name = "Wedding Salon",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Other Retail",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Notary",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Law Firm",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Accounting And Auditing",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Event Management",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 82L,
                            Name = "RealEstate",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Self-employed Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beauty",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Healthcare",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Sport",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Education",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Entertainment",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "HouseholdServices",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Auto",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Retail",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Other",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ClientCategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Loyal",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Permanent",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "VIP",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("CompanyTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = 0L,
                            Name = "Juridical Person",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 1L,
                            Name = "Physical Person",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DayTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DayTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Work Day",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Weekend",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeesSizeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SizeOfEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "1",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "2-5",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "6-10",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "11-20",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "21+",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("GenderId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Male",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Female",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CanViewEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CanManageEmployees",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "CanAddEmployee",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "CanChangeEmployeeWorkSchedule",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "CanManagePositions",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CanViewClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CanManageClients",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "CanAddService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "CanEditService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "CanDeleteService",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "CanViewOtherPeoplesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "CanCreateBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "CanAmendBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "CanRemoveBooking",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "CanAmendOtherEmployeesBookings",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "CanEditRoles",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "CanManageRolePolicies",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "CanEditCompanyInfo",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SystemRoleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CompanyAdmin",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CompanyAdminDeputy",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Specialist",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("WeekendTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WeekendTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Sick",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Leave",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Paid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Unpaid Holiday",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Standard Weekend (SAT/SUN)",
                            ParentId = 0L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Absence",
                            ParentId = 0L
                        });
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Specialist")
                        .WithMany("AssignedBookings")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.ClientCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.CompanyTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.EmployeesSizeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeesSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.CompanyBusinessArea", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("CompanyBusinessAreas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.PolicyRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.PolicyEntity", null)
                        .WithMany()
                        .HasForeignKey("Policy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.BusinessAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.ServiceEmployee", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany("ServiceEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Service", "Service")
                        .WithMany("ServiceEmployees")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.GenderEntity", null)
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.DayTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("DayType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Entities.User", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookingAggregatorApp.Domain.Enums.WeekendTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("WeekendType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CompanyBusinessAreas");

                    b.Navigation("Employees");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceEmployees");
                });

            modelBuilder.Entity("OnlineBookingAggregatorApp.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedBookings");

                    b.Navigation("ServiceEmployees");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
